apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-world
  namespace: hello-world
  annotations:
    # Replace with `terraform output -raw app_iam_role_arn`
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/demo-eks-dev-hello-world
